version: '3.1'

services:
  mongo:
    image: mongo:4.0.4
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017-27019:27017-27019'